server:
  port: 9999
app:
  logging:
    host: 192.168.6.182:5000
---
mybatis:
  type-aliases-package: br.com.ithappens.pdvredis.config
  mapper-locations: classpath*:**/mappers/*Mapper.xml

spring:
  profiles:
    active:
  application:
    name: pdv5-redis
  redis:
    database: 3
    host: localhost
    port: 6379
    password:
    timeout: 50000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
app:
  financeiro-datasource:
    url: jdbc:sqlserver://192.168.6.10:49260;databaseName=CADASTRO;applicationName=PDV_WS;
    username: gmcore
    password: dez2017!
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 5000
  tesouraria-datasource:
    url: jdbc:postgresql://192.168.6.152:5432/pdv_mateus
    username: syspdv
    password: XMpzymCPC4MR58
    hikari:
      maximumPoolSize: 10
      connectionTimeout: 5000
  backOffice-datasource:
    url: jdbc:postgresql://192.168.6.67:5432/maxipos
    username: maxipos
    password: maxipos!@#$
    hikari:
      maximumPoolSize: 10
      connectionTimeout: 5000
uri:
  mateus-controladoria:
    uri: http://192.168.6.90:9086/controladoria/v1